import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // components.json points the shadcn CLI at components/ui and hooks, so everything in
    // them is regenerated by `npx shadcn@latest add <component>`. Upstream synchronises
    // with an external system by setting state inside an effect - a matchMedia list in
    // use-mobile, the embla API in carousel. Rewriting that locally diverges from upstream
    // and is reverted the next time the component is added, which would fail CI on freshly
    // generated code. The rule is scoped off here rather than fought, and stays on
    // everywhere else, which is where application code lives.
    files: ["components/ui/**", "hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
