#!/usr/bin/env node
/**
 * Bundles each service's OpenAPI source in docs/30-protocol/openapi/src/, with the shared JSON:API
 * components, into one self-contained document: docs/30-protocol/openapi/<service>.openapi.yaml.
 * Those bundles are what Postman, Insomnia, Bruno and the published site import (ADR-0025).
 *
 * A hand-edited bundle silently disagrees with its source, and a document that does not lint imports
 * badly into exactly the tools it exists for — so CI runs this with --check and fails on either.
 *
 * Usage: node scripts/build-openapi.mjs          write the bundles, then lint them
 *        node scripts/build-openapi.mjs --check  fail if a bundle is stale or does not lint
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

// Keep in step with docs/10-architecture/tech-stack.md section 1.1.
const REDOCLY = '@redocly/cli@2.52.1';
const DIR = resolve('docs/30-protocol/openapi');
const SRC = join(DIR, 'src');
const SHARED = 'json-api.yaml';
const CHECK = process.argv.includes('--check');

const sources = readdirSync(SRC).filter((f) => f.endsWith('.yaml') && f !== SHARED).sort();
if (sources.length === 0) {
  console.error(`No service sources in ${SRC} — nothing to bundle is a failure, not a pass.`);
  process.exit(1);
}

const redocly = (args) => execFileSync('npx', ['--yes', REDOCLY, ...args], { encoding: 'utf8', stdio: 'pipe' });
const banner = (source) =>
  `# Generated by scripts/build-openapi.mjs from openapi/src/${source} and openapi/src/${SHARED}.\n` +
  '# Do not edit: change the source and run the script again.\n';

const problems = [];
const scratch = mkdtempSync(join(tmpdir(), 'orchestra-openapi-'));
try {
  for (const source of sources) {
    const name = source.replace(/\.yaml$/, '');
    const target = join(DIR, `${name}.openapi.yaml`);
    const bundled = join(scratch, `${name}.openapi.yaml`);

    redocly(['bundle', join(SRC, source), '--output', bundled]);
    const expected = banner(source) + readFileSync(bundled, 'utf8');

    if (CHECK) {
      if (!existsSync(target) || readFileSync(target, 'utf8') !== expected) {
        problems.push(`${name}.openapi.yaml is stale or missing`);
        continue;
      }
    } else {
      writeFileSync(target, expected);
    }

    try {
      redocly(['lint', target]);
    } catch (error) {
      problems.push(`${name}.openapi.yaml does not lint:\n${error.stdout ?? ''}${error.stderr ?? ''}`);
    }
  }
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

if (problems.length) {
  console.error(`\n${problems.length} problem(s) with the OpenAPI documents:\n`);
  for (const p of problems) console.error(`  ✗ ${p}`);
  console.error('\nRegenerate with: node scripts/build-openapi.mjs\n');
  process.exit(1);
}
console.log(`${CHECK ? 'Checked' : 'Bundled'} ${sources.length} OpenAPI document(s): ${sources.map((s) => s.replace(/\.yaml$/, '')).join(', ')}.`);
console.log('Every bundle matches its source and lints clean.');
